=== finos/architecture-as-code/calm/draft/2024-12/meta/core.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://calm.finos.org/draft/2024-12/meta/core.json",
  "title": "Common Architecture Language Model (CALM) Vocab",
  "properties": {
    "nodes": {
      "type": "array",
      "items": {
        "$ref": "#/defs/node"
      }
    },
    "relationships": {
      "type": "array",
      "items": {
        "$ref": "#/defs/relationship"
      }
    },
    "metadata": {
      "$ref": "#/defs/metadata"
    },
    "controls": {
      "$ref": "control.json#/defs/controls"
    },
    "flows": {
      "type": "array",
      "items": {
        "$ref": "flow.json#/defs/flow"
      }
    }
  },
  "defs": {
    "node": {
      "type": "object",
      "properties": {
        "unique-id": {
          "type": "string"
        },
        "node-type": {
          "$ref": "#/defs/node-type-definition"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "detailed-architecture": {
          "type": "string"
        },
        "data-classification": {
          "$ref": "#/defs/data-classification"
        },
        "run-as": {
          "type": "string"
        },
        "instance": {
          "type": "string"
        },
        "interfaces": {
          "type": "array",
          "items": {
            "$ref": "interface.json#/defs/interface-type"
          }
        },
        "controls": {
          "$ref": "control.json#/defs/controls"
        },
        "metadata": {
          "$ref": "#/defs/metadata"
        }
      },
      "required": [
        "unique-id",
        "node-type",
        "name",
        "description"
      ],
      "additionalProperties": true
    },
    "relationship": {
      "type": "object",
      "properties": {
        "unique-id": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "relationship-type": {
          "type": "object",
          "properties": {
            "interacts": {
              "$ref": "#/defs/interacts-type"
            },
            "connects": {
              "$ref": "#/defs/connects-type"
            },
            "deployed-in": {
              "$ref": "#/defs/deployed-in-type"
            },
            "composed-of": {
              "$ref": "#/defs/composed-of-type"
            }
          },
          "oneOf": [
            {
              "required": [
                "deployed-in"
              ]
            },
            {
              "required": [
                "composed-of"
              ]
            },
            {
              "required": [
                "interacts"
              ]
            },
            {
              "required": [
                "connects"
              ]
            }
          ]
        },
        "protocol": {
          "$ref": "#/defs/protocol"
        },
        "authentication": {
          "$ref": "#/defs/authentication"
        },
        "metadata": {
          "$ref": "#/defs/metadata"
        },
        "controls": {
          "$ref": "control.json#/defs/controls"
        }
      },
      "required": [
        "unique-id",
        "relationship-type"
      ],
      "additionalProperties": true
    },
    "data-classification": {
      "enum": [
        "Public",
        "Confidential",
        "Highly Restricted",
        "MNPI",
        "PII"
      ]
    },
    "protocol": {
      "enum": [
        "HTTP",
        "HTTPS",
        "FTP",
        "SFTP",
        "JDBC",
        "WebSocket",
        "SocketIO",
        "LDAP",
        "AMQP",
        "TLS",
        "mTLS",
        "TCP"
      ]
    },
    "authentication": {
      "enum": [
        "Basic",
        "OAuth2",
        "Kerberos",
        "SPNEGO",
        "Certificate"
      ]
    },
    "node-type-definition": {
      "enum": [
        "actor",
        "ecosystem",
        "system",
        "service",
        "database",
        "network",
        "ldap",
        "webclient",
        "data-assset"
      ]
    },
    "interacts-type": {
      "type": "object",
      "required": [
        "actor",
        "nodes"
      ],
      "properties": {
        "actor": {
          "type": "string"
        },
        "nodes": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string"
          }
        }
      }
    },
    "connects-type": {
      "type": "object",
      "properties": {
        "source": {
          "$ref": "interface.json#/defs/node-interface"
        },
        "destination": {
          "$ref": "interface.json#/defs/node-interface"
        }
      },
      "required": [
        "source",
        "destination"
      ]
    },
    "deployed-in-type": {
      "type": "object",
      "properties": {
        "container": {
          "type": "string"
        },
        "nodes": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string"
          }
        }
      }
    },
    "composed-of-type": {
      "required": [
        "container",
        "nodes"
      ],
      "type": "object",
      "properties": {
        "container": {
          "type": "string"
        },
        "nodes": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string"
          }
        }
      }
    },
    "metadata": {
      "type": "array",
      "items": {
        "type": "object"
      }
    }
  }
}

=== finos/architecture-as-code/cli/test_fixtures/getting-started/STEP-3/conference-signup-with-flow.arch.json
{
  "nodes": [
    {
      "unique-id": "conference-website",
      "name": "Conference Website",
      "description": "Website to sign up for a conference",
      "node-type": "webclient",
      "interfaces": [
        {
          "unique-id": "conference-website-url",
          "url": "[[ URL ]]"
        }
      ]
    },
    {
      "unique-id": "load-balancer",
      "name": "Load Balancer",
      "description": "The attendees service, or a placeholder for another application",
      "node-type": "network",
      "interfaces": [
        {
          "unique-id": "load-balancer-host-port",
          "host": "[[ HOST ]]",
          "port": -1
        }
      ]
    },
    {
      "unique-id": "attendees",
      "name": "Attendees Service",
      "description": "The attendees service, or a placeholder for another application",
      "node-type": "service",
      "interfaces": [
        {
          "unique-id": "attendees-image",
          "image": "[[ IMAGE ]]"
        },
        {
          "unique-id": "attendees-port",
          "port": -1
        }
      ]
    },
    {
      "unique-id": "attendees-store",
      "name": "Attendees Store",
      "description": "Persistent storage for attendees",
      "node-type": "database",
      "interfaces": [
        {
          "unique-id": "database-image",
          "image": "[[ IMAGE ]]"
        },
        {
          "unique-id": "database-port",
          "port": -1
        }
      ]
    },
    {
      "unique-id": "k8s-cluster",
      "name": "Kubernetes Cluster",
      "description": "Kubernetes Cluster with network policy rules enabled",
      "node-type": "system",
      "controls": {
        "security": {
          "description": "Security requirements for the Kubernetes cluster",
          "requirements": [
            {
              "control-requirement-url": "https://calm.finos.org/getting-started/controls/micro-segmentation.requirement.json",
              "control-config-url": "https://calm.finos.org/getting-started/controls/micro-segmentation.config.json"
            }
          ]
        }
      }
    }
  ],
  "relationships": [
    {
      "unique-id": "conference-website-load-balancer",
      "description": "Request attendee details",
      "protocol": "HTTPS",
      "relationship-type": {
        "connects": {
          "source": {
            "node": "conference-website"
          },
          "destination": {
            "node": "load-balancer"
          }
        }
      },
      "controls": {
        "security": {
          "description": "Security Controls for the connection",
          "requirements": [
            {
              "control-requirement-url": "https://calm.finos.org/getting-started/controls/permitted-connection.requirement.json",
              "control-config-url": "https://calm.finos.org/getting-started/controls/permitted-connection-http.config.json"
            }
          ]
        }
      }
    },
    {
      "unique-id": "load-balancer-attendees",
      "description": "Forward",
      "protocol": "mTLS",
      "relationship-type": {
        "connects": {
          "source": {
            "node": "load-balancer"
          },
          "destination": {
            "node": "attendees"
          }
        }
      },
      "controls": {
        "security": {
          "description": "Security Controls for the connection",
          "requirements": [
            {
              "control-requirement-url": "https://calm.finos.org/getting-started/controls/permitted-connection.requirement.json",
              "control-config-url": "https://calm.finos.org/getting-started/controls/permitted-connection-http.config.json"
            }
          ]
        }
      }
    },
    {
      "unique-id": "attendees-attendees-store",
      "description": "Store or request attendee details",
      "protocol": "JDBC",
      "relationship-type": {
        "connects": {
          "source": {
            "node": "attendees"
          },
          "destination": {
            "node": "attendees-store"
          }
        }
      },
      "controls": {
        "security": {
          "description": "Security Controls for the connection",
          "requirements": [
            {
              "control-requirement-url": "https://calm.finos.org/getting-started/controls/permitted-connection.requirement.json",
              "control-config-url": "https://calm.finos.org/getting-started/controls/permitted-connection-jdbc.config.json"
            }
          ]
        }
      }
    },
    {
      "unique-id": "deployed-in-k8s-cluster",
      "description": "Components deployed on the k8s cluster",
      "relationship-type": {
        "deployed-in": {
          "container": "k8s-cluster",
          "nodes": [
            "load-balancer",
            "attendees",
            "attendees-store"
          ]
        }
      }
    }
  ],
  "metadata": [
    {
      "kubernetes": {
        "namespace": "conference"
      }
    }
  ],
  "$schema": "https://calm.finos.org/getting-started/conference-signup.pattern.json",
  "flows": [
    "https://calm.finos.org/getting-started/flows/conference-signup.flow.json"
  ]
}

=== finos/architecture-as-code/shared/test_fixtures/command/generate/expected-output/conference-secure-signup-amended.arch.json
{
  "nodes": [
    {
      "unique-id": "conference-website",
      "name": "Conference Website",
      "description": "Website to sign up for a conference",
      "node-type": "webclient",
      "interfaces": [
        {
          "unique-id": "conference-website-url",
          "url": "https://calm.finos.org/amazing-website"
        }
      ]
    },
    {
      "unique-id": "load-balancer",
      "name": "Load Balancer",
      "description": "The attendees service, or a placeholder for another application",
      "node-type": "network",
      "interfaces": [
        {
          "unique-id": "load-balancer-host-port",
          "host": "localhost",
          "port": 80
        }
      ]
    },
    {
      "unique-id": "attendees",
      "name": "Attendees Service",
      "description": "The attendees service, or a placeholder for another application",
      "node-type": "service",
      "interfaces": [
        {
          "unique-id": "attendees-image",
          "image": "masteringapi/attendees-quarkus:ws-native-db"
        },
        {
          "unique-id": "attendees-port",
          "port": 8080
        }
      ]
    },
    {
      "unique-id": "attendees-store",
      "name": "Attendees Store",
      "description": "Persistent storage for attendees",
      "node-type": "database",
      "interfaces": [
        {
          "unique-id": "database-image",
          "image": "postgres-db:13"
        },
        {
          "unique-id": "database-port",
          "port": 5432
        }
      ]
    },
    {
      "unique-id": "k8s-cluster",
      "name": "Kubernetes Cluster",
      "description": "Kubernetes Cluster with network policy rules enabled",
      "node-type": "system",
      "controls": {
        "security": {
          "description": "Security requirements for the Kubernetes cluster",
          "requirements": [
            {
              "control-requirement-url": "https://calm.finos.org/workshop/controls/micro-segmentation.requirement.json",
              "control-config-url": "https://calm.finos.org/workshop/controls/micro-segmentation.config.json"
            }
          ]
        }
      }
    }
  ],
  "relationships": [
    {
      "unique-id": "conference-website-load-balancer",
      "description": "Request attendee details",
      "protocol": "HTTPS",
      "relationship-type": {
        "connects": {
          "source": {
            "node": "conference-website"
          },
          "destination": {
            "node": "load-balancer"
          }
        }
      },
      "controls": {
        "security": {
          "description": "Security Controls for the connection",
          "requirements": [
            {
              "control-requirement-url": "https://calm.finos.org/workshop/controls/permitted-connection.requirement.json",
              "control-config-url": "https://calm.finos.org/workshop/controls/permitted-connection-http.config.json"
            }
          ]
        }
      }
    },
    {
      "unique-id": "load-balancer-attendees",
      "description": "Forward",
      "protocol": "mTLS",
      "relationship-type": {
        "connects": {
          "source": {
            "node": "load-balancer"
          },
          "destination": {
            "node": "attendees"
          }
        }
      },
      "controls": {
        "security": {
          "description": "Security Controls for the connection",
          "requirements": [
            {
              "control-requirement-url": "https://calm.finos.org/workshop/controls/permitted-connection.requirement.json",
              "control-config-url": "https://calm.finos.org/workshop/controls/permitted-connection-http.config.json"
            }
          ]
        }
      }
    },
    {
      "unique-id": "attendees-attendees-store",
      "description": "Store or request attendee details",
      "protocol": "JDBC",
      "relationship-type": {
        "connects": {
          "source": {
            "node": "attendees"
          },
          "destination": {
            "node": "attendees-store"
          }
        }
      },
      "controls": {
        "security": {
          "description": "Security Controls for the connection",
          "requirements": [
            {
              "control-requirement-url": "https://calm.finos.org/workshop/controls/permitted-connection.requirement.json",
              "control-config-url": "https://calm.finos.org/workshop/controls/permitted-connection-jdbc.config.json"
            }
          ]
        }
      }
    },
    {
      "unique-id": "deployed-in-k8s-cluster",
      "description": "Components deployed on the k8s cluster",
      "relationship-type": {
        "deployed-in": {
          "container": "k8s-cluster",
          "nodes": [
            "load-balancer",
            "attendees",
            "attendees-store"
          ]
        }
      }
    }
  ],
  "metadata": [
    {
      "kubernetes": {
        "namespace": "conference"
      }
    }
  ],
  "flows": [
    "https://calm.finos.org/workshop/flows/conference-signup.flow.json"
  ],
  "$schema": "https://calm.finos.org/draft/2025-03/meta/calm.json"
}
