=== finos/architecture-as-code/calm/workshop/controls/permitted-connection.requirement.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://calm.finos.org/workshop/controls/permitted-connection.requirement.json",
  "title": "Permits a connection between two components in the architecture",
  "type": "object",
  "allOf": [
    {
      "$ref": "https://calm.finos.org/draft/2025-03/meta/control-requirement.json"
    }
  ],
  "properties": {
    "control-id": {
      "const": "security-002"
    },
    "name": {
      "const": "Permitted Connection"
    },
    "description": {
      "const": "Permits a connection on a relationship specified in the architecture"
    },
    "reason": {
      "type": "string",
      "description": "Reason for permitting the connection"
    },
    "protocol": {
      "$ref": "#/defs/protocol"
    }
  },
  "required": [
    "control-id",
    "name",
    "description",
    "reason",
    "protocol"
  ],
  "defs": {
    "protocol": {
      "enum": [
        "HTTP",
        "HTTPS",
        "FTP",
        "SFTP",
        "JDBC",
        "WebSocket",
        "SocketIO",
        "LDAP",
        "AMQP",
        "TLS",
        "mTLS",
        "TCP"
      ]
    }
  }
}

=== finos/architecture-as-code/calm/workshop/controls/permitted-connection-jdbc.config.json
{
  "$schema": "https://calm.finos.org/workshop/controls/permitted-connection.requirement.json",
  "control-id": "security-002",
  "name": "Permitted Connection",
  "description": "Permits a connection on a relationship specified in the architecture",
  "reason": "Permitted to allow the connection between application and database",
  "protocol": "JDBC"
}

=== finos/architecture-as-code/calm/workshop/controls/permitted-connection-http.config.json
{
  "$schema": "https://calm.finos.org/workshop/controls/permitted-connection.requirement.json",
  "control-id": "security-002",
  "name": "Permitted Connection",
  "description": "Permits a connection on a relationship specified in the architecture",
  "reason": "Required to enable flow between architecture components",
  "protocol": "HTTP"
}
